sudo: false
before_install:
  - "ulimit -u 4096"
script: ./bin/ci.sh
env:
  - CASSANDRA_VERSION=2.0.17 CASSANDRA_PROTOCOL_VERSION=2
  - CASSANDRA_VERSION=2.1.19 CASSANDRA_PROTOCOL_VERSION=3
  - CASSANDRA_VERSION=2.2.11 CASSANDRA_PROTOCOL_VERSION=4
  - CASSANDRA_VERSION=3.0.15 CASSANDRA_PROTOCOL_VERSION=4
#  - CASSANDRA_VERSION=3.11.1 CASSANDRA_PROTOCOL_VERSION=4
jdk:
  - oraclejdk8
