sudo: false
before_install:
  - "ulimit -u 4096"
script: ./bin/ci.sh
env:
  - CASSANDRA_VERSION=2.1.19
  - CASSANDRA_VERSION=2.2.11
  - CASSANDRA_VERSION=3.0.15
  - CASSANDRA_VERSION=3.1.1
jdk:
  - oraclejdk8
